### ISSUE TITLE
Error:java.lang.IllegalArgumentException: The transformer object (Python class __main__.feature_engineering) is not a supported Transformer

### ISSUE THREAD

**Issue by dev26** [jpmml/sklearn2pmml-plugin#12]
I have created a customer transformer for pre-processing.
I created a new class which extends BaseEstimator, TransformerMixin as follow:

```python
from sklearn.base import BaseEstimator, TransformerMixin
class feature_engineering(BaseEstimator, TransformerMixin):
  def __init__(self):
    print("Started processing")
    
  def fit(self, X, y = None):
    print("Fitting started")
    return self
  
  def transform(self, X, y = None):
    print("Transforming")
    specs_validation = X
    card = [(specs_validation['TICKET_TYPE']=='BT'), 
        (specs_validation['TICKET_TYPE']=='Non-BT')]
    values_card = [29,25]
    specs_validation['TICKET_NUM'] = np.select(card,values_card,default = 0)
    return specs_validation
```

I have successfully built a PMML pipeline by using the PMMLPipeline package but when I use sklearn2pmml to convert this into pmml. I got the following error:

```
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:853: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
Standard output is empty
Standard error:
Feb 23, 2022 7:06:54 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Feb 23, 2022 7:06:55 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 54 ms.
Feb 23, 2022 7:06:55 AM org.jpmml.sklearn.Main run
INFO: Converting..
Feb 23, 2022 7:06:55 AM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Feb 23, 2022 7:06:55 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: The transformer object (Python class __main__.feature_engineering) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:45)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:103)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:94)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
	at sklearn.TransformerUtil.getHead(TransformerUtil.java:107)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:195)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	... 7 more

Exception in thread "main" java.lang.IllegalArgumentException: The transformer object (Python class __main__.feature_engineering) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:45)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:103)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:94)
	at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:638)
	at sklearn.TransformerUtil.getHead(TransformerUtil.java:107)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:195)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Class.java:3369)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	... 7 more
```

**Comment by vruusmann** [comment]
> I have created a customer transformer for pre-processing.

You have implemented the Python-side of plugin.

Next, you need to implement the Java-side of plugin, and add the resulting plugin JAR file to the SkLearn2PMML package classpath.

Right now, the SkLearn2PMML plugin is complaining very openly that it cannot find the Java counterpart of your Python class (`__main__.feature_engineering`).

> def transform(self, X, y = None):

The business logic of your custom transformer could be very well handled using the `sklearn2pmml.preprocessing.ExpressionTransformer` class.

There is no need for a custom transformer class.

**Comment by dev26** [comment]
Thanks for the quick reply @vruusmann 
Will you please tell me how can I create the java-side of the plugin?

**Comment by vruusmann** [comment]
> Will you please tell me how can I create the java-side of the plugin?

Seriously - you'll be better off using `sklearn2pmml.preprocessing.ExpressionTransformer`.

Otherwise, you should start with reading the project's README, and checking out the related code examples:
https://github.com/jpmml/sklearn2pmml-plugin/blob/master/README.md

Python side:
https://github.com/jpmml/sklearn2pmml-plugin/tree/master/src/main/python

Java side:
https://github.com/jpmml/sklearn2pmml-plugin/tree/master/src/main/java

Please note that the SkLearn2PMML-Plugin project is slightly outdated in its current shape and form (depending on JPMML-SkLearn version 1.5.X APIs). It will be merged into the JPMML-SkLearn project soon.

**Comment by chenweidavis** [comment]
@vruusmann, hi, I made the jar and egg files with plug-in with JPMML-Sklearn 1.5.0, my sklearn2pmml is 0.84.2. During i convert the pmml with the comment : "sklearn2pmml(iris_pipeline, "Iris.pmml", user_classpath = [r"target/sklearn2pmml-plugin-1.0-SNAPSHOT.jar"])"
I met the error "Exception in thread "main" java.lang.NoSuchMethodError: org.jpmml.converter.FeatureUtil.createName(Ljava/lang/String;Ljava/util/List;)Lorg/dmg/pmml/FieldName;"
It looks like the version is not compatible. 
May I know which version of sklearn2pmml is compatible with JPMML-Sklearn 1.5.X.

**Comment by vruusmann** [comment]
> I met the error "Exception in thread "main" java.lang.NoSuchMethodError: 
>   org.jpmml.converter.FeatureUtil.createName(Ljava/lang/String;Ljava/util/List;)Lorg/dmg/pmml/FieldName;"
>

The `org.dmg.pmml.FieldName` class has been removed in the JPMML-Model 1.6.X development branch.

> May I know which version of sklearn2pmml is compatible with JPMML-Sklearn 1.5.X.

@chenweidavis If you're interested in software archaeology, then do the following:
1. Figure out what's your SkLearn2PMML package version.
2. Step into its `sklearn2pmml/resources` folder. See what is the version suffix of the `org.jpmml:jpmml-sklearn` artifact.
3. Use the same JPMML-SkLearn version in your custom plugin project.

Then it will work without any classpath issues.

**Comment by chenweidavis** [comment]
@vruusmann, Thanks a lot for your prompt response. I tried the similar steps you described before. My jpmml-sklearn is in 1.7.9 and i tried to modify the current pom.xml for generating new egg & jar files with newer jpmml-sklearn version. However, it failed.
What i do is that:
1. Modify the pom.xml - insert the below parts into xml file, and remove the old dependency part of jpmml. 
```
<!-- https://mvnrepository.com/artifact/org.jpmml/jpmml-sklearn -->
<dependency>
    <groupId>org.jpmml</groupId>
    <artifactId>jpmml-sklearn</artifactId>
    <version>1.7.9</version>
    <type>pom</type>
</dependency>
```

2. Re-run the "mvn clean install"
3. Meet the error as below:
"Failed to execute goal on project sklearn2pmml-plugin: Could not resolve dependencies for project sklearn2pmml:sklearn2pmml-plugin:jar:1.0-SNAPSHOT: org.jpmml:jpmml-sklearn:jar:1.7.9 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]"

Hence, May i know how to modify the pom.xml file to generate the plugin files successfully. Thanks!!

**Comment by chenweidavis** [comment]
@vruusmann, the modification part in pom.xml
""" 
    <dependency>
       <groupId>org.jpmml</groupId>
       <artifactId>jpmml-sklearn</artifactId>
         <version>1.7.9</version>
      <type>pom</type>
    </dependency>"""

**Comment by vruusmann** [comment]
> However, it failed.

The JPMML-SkLearn project was modularized when upgrading from 1.6.X to 1.7.X. One of the visible changes is that the main artifact was renamed from `org.jpmml:jpmml-sklearn` to `org.jpmml:pmml-sklearn` (note the missing "j" prefix in the second component!).

@chenweidavis You first asked about JPMML-SkLearn version 1.5.X, hence my suggestion to use `org.jpmml:jpmml-sklearn`. Now you ask about JPMML-SkLearn version 1.7.X, and now my suggestion changes to `org.jpmml:pmml-sklearn`. See the difference?

First figure out which JPMML-SkLearn development branch are you targeting - 1.5.X, 1.7.X, or something else. After that, add the appropriate artifact into your `pom.xml`.

**Comment by chenweidavis** [comment]
@vruusmann, thanks a lot for ur help. The issue was solved at my side.
