### ISSUE TITLE
Adding Transformer Weights

### ISSUE THREAD

**Issue by nejatb** [jpmml/sklearn2pmml-plugin#2]
Can we add transformerWeights similar to http://scikit-learn.org/stable/modules/generated/sklearn.pipeline.FeatureUnion.html? If not already supported but possible to support, can you briefly describe the procedure and steps that one needs to take to add this capability?

Is this similar to creating a new custom transformer?

**Comment by vruusmann** [comment]
Migrated to https://github.com/jpmml/jpmml-sklearn/issues/63
