### ISSUE TITLE
Issues while creating a custom function and its subsequent Java class

### ISSUE THREAD

**Issue by timjeti** [jpmml/sklearn2pmml-plugin#3]
Hello Sir
 i tried to write a custom class ItemSelector which can be run using sklearn2pmml.

The structure of the dataset Auto is given below-
![dset](https://user-images.githubusercontent.com/37206421/37206022-07870ac4-23bd-11e8-9c31-ded4d1bb93a7.JPG)

The custom Itemselector class is:

```
class ItemSelector(TransformerMixin):
	def __init__(self, key):
		self.key = key
	def transform(self, X, y=None):
		return X[[self.key]]
 
	def fit(self, X, y=None):
		return self
```

This ItemSelector is just returning values of the target attribute and not doing any feature engineering.For example in case of Auto dataset if the value in key argument is cylinders then it should return all the elements stored in the cylinders attribute

I am using pipeline to create the object like this:-

```
pipdi=PMMLPipeline([('f1',FeatureUnion(            [
                ('p1',Pipeline([('extract',ItemSelector(key='weight'))])),
            ])),
               ('estimator', ensemble.RandomForestRegressor())])
```

Everything works well until this step-

`sklearn2pmml(pipdi, "Deciscion.pmml", user_classpath = ["sklearn2pmml-plugin-1.0-SNAPSHOT.jar"],with_repr=True,debug=True)`

After this step i receive an error:-

> ---------------------------------------------------------------------------
> CalledProcessError                        Traceback (most recent call last)
> C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug)
>     269                 try:
> --> 270                         subprocess.check_call(cmd)
>     271                 except CalledProcessError:
> 
> C:\ProgramData\Anaconda3\lib\subprocess.py in check_call(*popenargs, **kwargs)
>     290             cmd = popenargs[0]
> --> 291         raise CalledProcessError(retcode, cmd)
>     292     return 0
> 
> CalledProcessError: Command '['java', '-cp', 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\guava-20.0.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\istack-commons-runtime-3.0.5.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\jaxb-core-2.3.0.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\jaxb-runtime-2.3.0.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\jcommander-1.48.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\jpmml-converter-1.2.6.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\jpmml-lightgbm-1.1.3.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\jpmml-sklearn-1.4.5.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\jpmml-xgboost-1.2.4.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-agent-1.3.8.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-model-1.3.8.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-model-metro-1.3.8.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-schema-1.3.8.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\pyrolite-4.19.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\serpent-1.18.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\slf4j-api-1.7.25.jar;C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn2pmml\\resources\\slf4j-jdk14-1.7.25.jar;sklearn2pmml-plugin-1.0-SNAPSHOT.jar', 'org.jpmml.sklearn.Main', '--pkl-pipeline-input', 'C:\\Users\\jeti\\AppData\\Local\\Temp\\pipeline-t83x58na.pkl.z', '--pmml-output', 'Deciscion.pmml']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-74-3ef4800166b3> in <module>()
> ----> 1 sklearn2pmml(pipdi, "Deciscion.pmml", user_classpath = ["sklearn2pmml-plugin-1.0-SNAPSHOT.jar"],with_repr=True,debug=False)
> 
> C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug)
>     270                         subprocess.check_call(cmd)
>     271                 except CalledProcessError:
> --> 272                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams")
>     273         finally:
>     274                 if debug:
> 
> RuntimeError: The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams

As stated by you in earlier issues,i have to write a java file corresponding to the python class ItemSelector, but i am unable to create a proper java file for this use-case as i am unaware of what different inbuilt classes are performing.

I would also like to add that i do not want to display anything in the pmml file relating to the class ItemSelector. I just want to bypass the error so that it generates a pmml file.
The java file for ItemSelector which i have created returns null because of which i think i am getting those errors.I have to put some proper information there but i am unaware which way to go.

The java snippet is:

```
package com.mycompany;
import java.util.ArrayList;
import java.util.List;
import org.jpmml.converter.BinaryFeature;
import org.jpmml.converter.ContinuousFeature;
import org.jpmml.converter.Feature;
import org.jpmml.converter.PowerFeature;
import org.jpmml.sklearn.SkLearnEncoder;
import sklearn.Transformer;
public class ItemSelector extends Transformer {
//	public List att_key;
	public ItemSelector(String module, String name)
	{
		super(module, name);
	}

	@Override
	public List<Feature> encodeFeatures(List<Feature> features, SkLearnEncoder encoder){

		return null;
	}
	
	public String getKey()
	{
		return (String)get("key");
	}

}
```

I would like to thank you for your time.

**Comment by vruusmann** [comment]
Your `ItemSelector` is choosing a column from DataFrame in order to perform column-oriented feature engineering on it. This functionality is already available in the form of `sklearn_pandas.DataFrameMapper` class - consider using it instead of pursuing your own implementation.

For example, here's an example about doing column-oriented feature engineering for the Auto-MPG dataset:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L379-L408

You appear to be using a slightly outdated SkLearn2PMML/JPMML-SkLearn version (the current one is `0.31.1`); after upgrading you should see more details about the exception.

At the moment I believe it is some kind of `java.lang.NullPointerException`, because the Java side of your `ItelSelector` class is returning `null` (in the method `ItemSelector#encodeFeatures(List<Feature>, SkLearnEncoder)`), which is not permitted (invalid return state).
