### ISSUE TITLE
Meet Error: java.lang.IllegalArgumentException: The value object (Python class src.main.python.com.mycompany.Aggregator) is not a supported Transformer

### ISSUE THREAD

**Issue by stonezaici** [jpmml/sklearn2pmml-plugin#5]
Hi vruusmann,

I have download the code(sklearn2pmml-plugin), and I did the following the step:
1. following step in README.md build the project, get the *.egg file and jar file, 
2. then I open pycharm create a new py file: test_poc.py under /src/main/python  and paste the code from README.md into it, cause I don't find any file in git include the code.
3. run the test_poc.py, then meet the error at last step: **sklearn2pmml(iris_pipeline, "Iris.pmml", user_classpath = [r"D:\2_software\Git\Git_Code\sklearn2pmml-plugin\target\sklearn2pmml-plugin-1.0-SNAPSHOT.jar"])**
Error Msg: 
Standard output is empty
Standard error:
 06, 2019 3:41:01  org.jpmml.sklearn.Main run
INFO: Parsing PKL..
 06, 2019 3:41:01  org.jpmml.sklearn.Main run
INFO: Parsed PKL in 22 ms.
 06, 2019 3:41:01  org.jpmml.sklearn.Main run
INFO: Converting..
 06, 2019 3:41:01  org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: The value object (Python class src.main.python.com.mycompany.Aggregator) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:72)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.lang.Class.cast(Unknown Source)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 9 more
4. Furthermore, I also note the file: sklearn2pmml.properties, seems it missed sth, its content as below:
com.mycompany.Aggregator =
com.mycompany.PowerFunction =
com.mycompany.StringNormalizer =

in README.md file said it is "The mappings from Python classes to Java classes."  so how to define the part behind "=" ?

could you please help on this?

thanks a lot :)
Allen

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: The value object (Python class src.main.python.com.mycompany.Aggregator) is not a supported Transformer

There's a `src.main.python` module prefix to your custom transformer class name, which shouldn't be there.

You can develop inside the `src/main/python` directory, but when building JAR and EGG files, you should step back to the project root directory.

> I also note the file: sklearn2pmml.properties, seems it missed sth

The format is: `<Python class name> = <JPMML-SkLearn converter class name>`

If the right-hand side is exactly the same as the left-hand side, then it may be omitted - it's a convenience feature, which also improves the readability of `sklearn2pmml.properties` files.

It's typically the case that Python class names contain extra "module layers" to their class names.

**Comment by stonezaici** [comment]
Hi vruusmann,

Thank you very much for your swift respond. :)
Yes, I need to set python folder as source root in pycharm then issue fixed.

Thanks a lot.
Allen
