### ISSUE TITLE
Question about writing the custom Estimator

### ISSUE THREAD

**Issue by pwittchen** [jpmml/sklearn2pmml-plugin#9]
Hi,

Thanks for sharing great project!
I have a question. Can you please provide an example of the implementation of the custom Estimator (e.g. extending `OneClassSVM` estimator) using this plugin mechanism? Creating custom estimators is not clear for me and having a simple example will be very helpful.

Regards,
Piotr

**Comment by vruusmann** [comment]
> Can you please provide an example of the implementation of the custom Estimator?

Have you tried developing custom transformers already? Custom estimators are almost identical, the only difference is that on the Java side you'd be extending some `sklearn.Estimator` subclass (most commonly, `sklearn.Classifier` or `sklearn.Regressor`).

> extending OneClassSVM estimator

The class hierarchy on the Java side should mimic that of the Python side.

If you're extending `OneClassSVM` Python class, then you should be extending `sklearn.svm.OneClassSVM` Java class on the Java side.

Please note that `OneClassSVM` is an unsupervised learning algorithm (does not specify a target field(s)), so it's important to override `sklearn.Estimator#isSupervised()` and return `false` there.

> Creating custom estimators is not clear for me and having a simple example will be very helpful.

Just see any estimator class under the `sklearn2pmml` package prefix. For example, the `SelectFirstEnsemble` class implements a conditionally executed model chain: https://github.com/jpmml/sklearn2pmml/blob/0.55.4/sklearn2pmml/ensemble/__init__.py#L127-L199 and https://github.com/jpmml/jpmml-sklearn/blob/1.5.35/src/main/java/sklearn2pmml/ensemble/SelectFirstClassifier.java

Be sure to register your classes in the `META-INF/sklearn2pmml.properties` file!
https://github.com/jpmml/jpmml-sklearn/blob/1.5.35/src/main/resources/META-INF/sklearn2pmml.properties#L161-L162

**Comment by pwittchen** [comment]
Thanks a lot for the quick reply. :)
